language: php

php:
  - 5.5
  - 5.4
  - 5.3

before_install:
  - cd /home/travis/build
  - mkdir www
  - mkdir log
  - sudo apt-get update
  - sudo apt-get install apache2
  - sudo a2enmod actions
  - sudo a2enmod rewrite
  - echo "export PATH=/home/vagrant/.phpenv/bin:$PATH" | sudo tee -a /etc/apache2/envvars > /dev/null
  - echo "$(curl -fsSL https://gist.github.com/roderik/16d751c979fdeb5a14e3/raw/gistfile1.txt)" | sudo tee /etc/apache2/conf.d/phpconfig > /dev/null
  - echo "$(curl -fsSL https://gist.github.com/addshore/7012119/raw/1ac2ee8f257e2959ae592f5ab3f166f42d839457/gistfile1.txt)" | sed -e "s,PATH,`pwd`/www,g" | sudo tee /etc/apache2/sites-available/default > /dev/null
  - sudo service apache2 restart

install:
  - cd /home/travis/build/www
  - git clone https://gerrit.wikimedia.org/r/p/mediawiki/core.git wiki --depth 1
  - cd wiki
  - php maintenance/install.php --dbtype sqlite --dbuser root --dbname its_a_mw --dbpath $(pwd) --pass integration TravisWiki Test
  - cd extensions
  # Install extensions...
  - cd -
  - php maintenance/update.php --quick

before_script:
  - chmod -R 777 /home/travis/build/www
  - cd /home/travis/build/addshore/addframe

script:
  - phpunit --configuration tests/unit.xml
  # Only run integration tests on 5.4 ( apache seems to fail on 5.3 see https://travis-ci.org/addwiki/addframe/jobs/12631703 )
  - if php --version | grep -q 5.4; then phpunit --configuration tests/integration.xml; fi

after_failure:
  - cat /home/travis/build/log/error.log

notifications:
  irc:
    channels:
      - "chat.freenode.net##add"
    on_success: change
    on_failure: always
  email:
    recipients:
      - johnflewis93@gmail.com
    on_success: change
    on_failure: always
