#!/bin/bash

ps -o sz,etime,pid,comm,args -U addshore | grep g.php | grep -v grep | perl -ane '($m,$s) = split /:/,$F[1]; $kb=$F[0]; $pid = $F[2]; if(($m>240)||($kb>100000)) {print "$m :: $s $kb $pid\n"; kill 9, $pid;}'

ps -o sz,etime,pid,comm,args -U addshore | grep list.php | grep -v grep | perl -ane '($m,$s) = split /:/,$F[1]; $kb=$F[0]; $pid = $F[2]; if(($m>240)||($kb>100000)) {print "$m :: $s $kb $pid\n"; kill 9, $pid;}'

ps -o sz,etime,pid,comm,args -U addshore | grep run.php | grep -v grep | perl -ane '($m,$s) = split /:/,$F[1]; $kb=$F[0]; $pid = $F[2]; if(($m>60)||($kb>100000)) {print "$m :: $s $kb $pid\n"; kill 9, $pid;}'